In [50]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\Desktop\FINANCIAL INCLUSION (GLOBAL FINDEX)\ACCOUNT_OWNERSHIP,MOBILE_MONEY_ACCOUNT, DIGITAL_PAYMENTS.csv")
df_internet_users = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\INDIVIDUAL USING INTERNET (% OF POPULATION).csv"
,skiprows= 4)
df_GDP = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\GDP per CAPITA.csv"
,skiprows = 4)
df_Urban_Population = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\URBAN_POPULATION(% OF TOTAL POPULATION).csv",
skiprows = 4)
df_Poverty_Ratio = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\POVERTY HEAD COUNT RATIO AT NATIONAL POVERTY LINES.csv",
skiprows = 4)
df_Mobile_Subscription = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\MOBILE CELLULAR SUBSCRIPTION PER 100 PEOPLE.csv",
skiprows = 4)
df_Bank_Branches = pd.read_csv(r"C:\Users\hp\Desktop\WORLD DEVELOPMENT INDICATORS(WDI)\COMMERCIAL BRANCHES (per 100,000 adults).csv",
skiprows = 4)
df_bank_account = pd.read_csv(r"C:\Users\hp\Desktop\FINANCIAL INCLUSION (GLOBAL FINDEX)\Bank_Account_financial_institution_account.csv")

In [51]:
df.head(2)

,Country Name,Country Code,Series Name,Series Code,2011 [YR2011],2014 [YR2014],2017 [YR2017],2021 [YR2021],2022 [YR2022],2024 [YR2024]
0,Angola,AGO,Account (% age 15+),account.t.d,39.2035423430619,29.3181213047365,..,..,..,..
1,Angola,AGO,Mobile money account (% age 15+),mobileaccount.t.d,..,..,..,..,..,..

RENAMING THE YEARS

In [52]:
df_long = df.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_long.head(2)

,Country Name,Country Code,Series Name,Series Code,2011,2014,2017,2021,2022,2024
0,Angola,AGO,Account (% age 15+),account.t.d,39.2035423430619,29.3181213047365,..,..,..,..
1,Angola,AGO,Mobile money account (% age 15+),mobileaccount.t.d,..,..,..,..,..,..

CONVERTING YEARS INTO ONE COLUMN(MELT)

In [53]:
df_long = df_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

In [54]:
df_long.head(15)

,Country Name,Country Code,Series Name,Year,Value
0,Angola,AGO,Account (% age 15+),2011,39.2035423430619
1,Angola,AGO,Mobile money account (% age 15+),2011,..
2,Angola,AGO,Digitally enabled account (% age 15+),2011,..
3,Angola,AGO,Made a digital payment (% age 15+),2011,..
4,Benin,BEN,Account (% age 15+),2011,10.4639370332736
5,Benin,BEN,Mobile money account (% age 15+),2011,..
6,Benin,BEN,Digitally enabled account (% age 15+),2011,..
7,Benin,BEN,Made a digital payment (% age 15+),2011,..
8,Botswana,BWA,Account (% age 15+),2011,30.2600142850791
9,Botswana,BWA,Mobile money account (% age 15+),2011,..
10,Botswana,BWA,Digitally enabled account (% age 15+),2011,..
11,Botswana,BWA,Made a digital payment (% age 15+),2011,..
12,Burkina Faso,BFA,Account (% age 15+),2011,13.3530920184137
13,Burkina Faso,BFA,Mobile money account (% age 15+),2011,..
14,Burkina Faso,BFA,Digitally enabled account (% age 15+),2011,..

In [55]:
df_long.loc[
    df_long[
        ["Country Name", "Country Code", "Series Name", "Value"]
    ].isna().any(axis=1),
    ["Country Name", "Country Code", "Series Name", "Value"]
]

,Country Name,Country Code,Series Name,Value
172,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN
174,NaN,NaN,NaN,NaN
175,Data from database: Global Findex database,NaN,NaN,NaN
176,Last Updated: 10/06/2025,NaN,NaN,NaN
349,NaN,NaN,NaN,NaN
350,NaN,NaN,NaN,NaN
351,NaN,NaN,NaN,NaN
352,Data from database: Global Findex database,NaN,NaN,NaN
353,Last Updated: 10/06/2025,NaN,NaN,NaN
526,NaN,NaN,NaN,NaN
527,NaN,NaN,NaN,NaN
528,NaN,NaN,NaN,NaN
529,Data from database: Global Findex database,NaN,NaN,NaN
530,Last Updated: 10/06/2025,NaN,NaN,NaN
703,NaN,NaN,NaN,NaN
704,NaN,NaN,NaN,NaN
705,NaN,NaN,NaN,NaN
706,Data from database: Global Findex database,NaN,NaN,NaN
707,Last Updated: 10/06/2025,NaN,NaN,NaN
880,NaN,NaN,NaN,NaN
881,NaN,NaN,NaN,NaN
882,NaN,NaN,NaN,NaN
883,Data from database: Global Findex database,NaN,NaN,NaN
884,Last Updated: 10/06/2025,NaN,NaN,NaN
1057,NaN,NaN,NaN,NaN
1058,NaN,NaN,NaN,NaN
1059,NaN,NaN,NaN,NaN
1060,Data from database: Global Findex database,NaN,NaN,NaN
1061,Last Updated: 10/06/2025,NaN,NaN,NaN

REMOVING NAN VALUES

In [56]:
df_long[['Country Name','Country Code','Series Name']].isna().sum()

Country Name    18
Country Code    30
Series Name     30
dtype: int64

In [57]:
df_long = df_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

In [58]:
 df_long.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Year            0
Value           0
dtype: int64

CREATING A PIVOT FOR SERIES NAMES TO APPEAR IN INDIVIDUAL COLUMNS

In [59]:
df_final = df_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_final.columns.name = None

df_final

,Country Name,Country Code,Year,Account (% age 15+),Digitally enabled account (% age 15+),Made a digital payment (% age 15+),Mobile money account (% age 15+)
0,Angola,AGO,2011,39.2035423430619,..,..,..
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..
2,Angola,AGO,2017,..,..,..,..
3,Angola,AGO,2021,..,..,..,..
4,Angola,AGO,2022,..,..,..,..
...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057
256,Zimbabwe,ZWE,2022,..,..,..,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992

In [60]:
df_final = df_final.rename(columns = {
    'Country Name':'Country',
    'Country Code':'Code',
    'Account  (% age 15+)':'Account',
    'Digitally enabled account  (% age 15+)':'Digitally enabled Account',
    'Made a digital payment  (% age 15+)':'Made a Digital Payment',
    'Mobile money account  (% age 15+)':'Mobile Money Account'


})

df_final

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account
0,Angola,AGO,2011,39.2035423430619,..,..,..
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..
2,Angola,AGO,2017,..,..,..,..
3,Angola,AGO,2021,..,..,..,..
4,Angola,AGO,2022,..,..,..,..
...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057
256,Zimbabwe,ZWE,2022,..,..,..,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992

In [61]:
df_final.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING INTERNET USERS DATAFRAME

In [62]:
year_cols = [col for col in df_internet_users.columns if col[:4].isdigit()]

df_internet_users_long = df_internet_users.melt(
    id_vars=["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name="Year",
    value_name="Value"
)

df_internet_users_long = df_internet_users_long[
    df_internet_users_long['Year'].isin(df_final['Year'].unique())
]

df_internet_users_long= df_internet_users_long[df_internet_users_long["Country Name"].isin(df_final['Country'].unique())]

df_internet_users_long = (df_internet_users_long.rename(columns={"Value":"Internet_users",'Country Name':'Country',
'Country Code': 'Code'})
                        .drop(columns = ['Indicator Name'])
                      )
df_internet_users_long[['Country','Code','Internet_users']].isna().sum()

Country            0
Code               0
Internet_users    11
dtype: int64

In [63]:
df_internet_users_long.loc[
    df_internet_users_long[
        ["Country", "Code", "Year", "Internet_users"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "Internet_users"]
]

                        Country Code  Year  Internet_users
13772                     Sudan  SDN  2011             NaN
13782               South Sudan  SSD  2011             NaN
14570                     Sudan  SDN  2014             NaN
15205          Congo, Dem. Rep.  COD  2017             NaN
16260  Central African Republic  CAF  2021             NaN
16432                     Sudan  SDN  2021             NaN
16442               South Sudan  SSD  2021             NaN
16698                     Sudan  SDN  2022             NaN
16708               South Sudan  SSD  2022             NaN
17230                     Sudan  SDN  2024             NaN
17240               South Sudan  SSD  2024             NaN

In [64]:
df_internet_users_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING GPD PER CAPITA DATASET

In [65]:
df_GDP_long = df_GDP.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_GDP_long = df_GDP_long[df_GDP_long['Year'].isin(df_final['Year'].unique())]
df_GDP_long = df_GDP_long[df_GDP_long['Country Name'].isin(df_final['Country'].unique())]

df_GDP_long = (df_GDP_long.rename(columns={"Value":"GDP",
'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_GDP_long

df_GDP_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

In [66]:
df_GDP_long.loc[
    df_GDP_long[
        ["Country", "Code", "Year", "GDP"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "GDP"]
]

           Country Code  Year  GDP
15378  South Sudan  SSD  2017  NaN
16442  South Sudan  SSD  2021  NaN
16708  South Sudan  SSD  2022  NaN
17240  South Sudan  SSD  2024  NaN

In [67]:
df_GDP_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING df_Urban_Population

In [68]:
df_Urban_Population_long= df_Urban_Population.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_Urban_Population_long= df_Urban_Population_long[df_Urban_Population_long['Year'].isin(df_final['Year'].unique())]
df_Urban_Population_long =df_Urban_Population_long[df_Urban_Population_long['Country Name'].isin(df_final['Country'].unique())]

df_Urban_Population_long = (df_Urban_Population_long.rename(columns={"Value":"Urban_population",'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_Urban_Population_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

In [69]:
df_Urban_Population_long.loc[
    df_Urban_Population_long[
        ["Country", "Code", "Year", "Urban_population"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "Urban_population"]
]

Empty DataFrame
Columns: [Country, Code, Year, Urban_population]
Index: []

In [70]:
df_Urban_Population_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING df_Povert_Ratio

In [71]:
df_poverty_ratio_long= df_Poverty_Ratio .melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_poverty_ratio_long= df_poverty_ratio_long[df_poverty_ratio_long['Year'].isin(df_final['Year'].unique())]
df_poverty_ratio_long =df_poverty_ratio_long[df_poverty_ratio_long['Country Name'].isin(df_final['Country'].unique())]

df_poverty_ratio_long = (df_poverty_ratio_long.rename(columns={"Value":"Poverty_ratio",'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_poverty_ratio_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

In [72]:
df_poverty_ratio_long.loc[
    df_poverty_ratio_long[
        ["Country", "Code", "Year", "Poverty_ratio"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "Poverty_ratio"]
]

            Country Code  Year  Poverty_ratio
13570        Angola  AGO  2011            NaN
13582       Burundi  BDI  2011            NaN
13584         Benin  BEN  2011            NaN
13585  Burkina Faso  BFA  2011            NaN
13599      Botswana  BWA  2011            NaN
...             ...  ...   ...            ...
17270      Tanzania  TZA  2024            NaN
17271        Uganda  UGA  2024            NaN
17287  South Africa  ZAF  2024            NaN
17288        Zambia  ZMB  2024            NaN
17289      Zimbabwe  ZWE  2024            NaN

[222 rows x 4 columns]

In [73]:
df_poverty_ratio_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING df_Mobile_Subscription

In [74]:
df_mobile_subscription_long= df_Mobile_Subscription.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_mobile_subscription_long= df_mobile_subscription_long[df_mobile_subscription_long['Year'].isin(df_final['Year'].unique())]
df_mobile_subscription_long =df_mobile_subscription_long[df_mobile_subscription_long['Country Name'].isin(df_final['Country'].unique())]

df_mobile_subscription_long = (df_mobile_subscription_long.rename(columns={"Value":"Mobile_cellular_subscription",'Country Name':'Country',
'Country Code': 'Code'})

                       .drop(columns=["Indicator Name"]))

df_mobile_subscription_long[['Country','Code','Mobile_cellular_subscription']].isna().sum()

Country                          0
Code                             0
Mobile_cellular_subscription    11
dtype: int64

In [75]:
df_mobile_subscription_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING df_Bank_Branches

In [76]:
df_bank_branches_long= df_Bank_Branches.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_bank_branches_long= df_bank_branches_long[df_bank_branches_long['Year'].isin(df_final['Year'].unique())]
df_bank_branches_long =df_bank_branches_long[df_bank_branches_long['Country Name'].isin(df_final['Country'].unique())]

df_bank_branches_long = (df_bank_branches_long.rename(columns={"Value":"Commercial_bank_branches",
'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))




df_bank_branches_long

df_bank_branches_long[['Country','Code']].isna().sum()

df_bank_branches_long

            Country Code  Year  Commercial_bank_branches
13570        Angola  AGO  2011                  8.144849
13582       Burundi  BDI  2011                  2.410982
13584         Benin  BEN  2011                  3.186366
13585  Burkina Faso  BFA  2011                  2.028757
13599      Botswana  BWA  2011                  8.320601
...             ...  ...   ...                       ...
17270      Tanzania  TZA  2024                       NaN
17271        Uganda  UGA  2024                       NaN
17287  South Africa  ZAF  2024                       NaN
17288        Zambia  ZMB  2024                       NaN
17289      Zimbabwe  ZWE  2024                       NaN

[252 rows x 4 columns]

In [77]:
df_bank_branches_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING df_bank_account

In [78]:
df_bank_account_long = df_bank_account.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}
)
df_bank_account_long = df_bank_account_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)
df_bank_account_long = df_bank_account_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)
df_final_bank_account = df_bank_account_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_final_bank_account.columns.name = None

df_final_bank_account = df_final_bank_account.rename(columns = {
    'Country Name':'Country',
    'Country Code':'Code',
    'Bank or similar financial institution account  (% age 15+)':'Bank Account',
    
})

df_final_bank_account

      Country Code  Year      Bank Account
0      Angola  AGO  2011  39.2035423430619
1      Angola  AGO  2014  29.3181213047365
2      Angola  AGO  2017                ..
3      Angola  AGO  2021                ..
4      Angola  AGO  2022                ..
..        ...  ...   ...               ...
253  Zimbabwe  ZWE  2014  17.1894919246347
254  Zimbabwe  ZWE  2017  28.1799818696936
255  Zimbabwe  ZWE  2021  29.2496946936906
256  Zimbabwe  ZWE  2022                ..
257  Zimbabwe  ZWE  2024  21.5661530622998

[258 rows x 4 columns]

In [79]:
print(df_bank_account.columns.tolist())

['Country Name', 'Country Code', 'Series Name', 'Series Code', '2011 [YR2011]', '2014 [YR2014]', '2017 [YR2017]', '2021 [YR2021]', '2022 [YR2022]', '2024 [YR2024]']

In [80]:
for df in [df_final, 
df_internet_users_long, 
df_GDP_long, 
df_mobile_subscription_long, 
df_bank_branches_long,
df_poverty_ratio_long, 
df_Urban_Population_long,
df_final_bank_account]:
    df["Year"] = df["Year"].astype(int)

MERGING THE DATASETS

In [81]:
master = df_final.copy()

datasets = [
   df_internet_users_long, 
   df_GDP_long, 
   df_mobile_subscription_long,
   df_bank_branches_long,
   df_poverty_ratio_long, 
   df_Urban_Population_long,df_final_bank_account
]

for df in datasets:
    master = master.merge(
        df,
        on=["Country","Code","Year"],
        how="left"
    )

master

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,Mobile_cellular_subscription,Commercial_bank_branches,Poverty_ratio,Urban_population,Bank Account
0,Angola,AGO,2011,39.2035423430619,..,..,..,4.700000,5184.152691,49.851526,8.144849,NaN,60.843161,39.2035423430619
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..,21.362341,5649.687625,51.738439,10.018160,NaN,62.723116,29.3181213047365
2,Angola,AGO,2017,..,..,..,..,26.000000,2790.718869,44.068209,9.877548,NaN,65.085053,..
3,Angola,AGO,2021,..,..,..,..,34.556499,2303.908127,44.386869,8.035832,NaN,68.252416,..
4,Angola,AGO,2022,..,..,..,..,35.838001,3682.113151,66.600807,7.583594,NaN,69.050619,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691,16.364740,1372.915262,83.046061,14.668721,NaN,33.162808,17.1894919246347
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818,24.400000,3445.449410,95.136683,5.402445,30.4,34.701495,28.1799818696936
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057,32.592400,2613.605421,90.253849,5.818109,NaN,37.869206,29.2496946936906
256,Zimbabwe,ZWE,2022,..,..,..,..,36.256500,2536.400502,88.995831,5.542454,NaN,38.705521,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992,41.642799,2497.203322,94.245175,NaN,NaN,39.893372,21.5661530622998

In [82]:
cols_to_num = [
    "Account",
    "Digitally enabled Account",
    "Made a Digital Payment",
    "Mobile Money Account",
    "Internet_users",
    "GDP",
    "Mobile_cellular_subscription",
    "Commercial_bank_branches",
    "Poverty_ratio",
    "Urban_population",
    "Bank Account"
]

master[cols_to_num] = master[cols_to_num].apply(
    lambda x: pd.to_numeric(x, errors="coerce").round(2)
)

In [93]:
master["Financial_Institution_Account_only"] = master["Account"] - (master["Mobile Money Account"])

master["Mobile_Money_Account_only"] = master["Account"] - (master["Bank Account"])

master["Both_Accounts"] = master["Account"] - (master["Financial_Institution_Account_only"] + master["Mobile_Money_Account_only"])

In [95]:
master[master["Country"] == "South Africa"].head()

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,Mobile_cellular_subscription,Commercial_bank_branches,Poverty_ratio,Urban_population,Bank Account,Financial_Institution_Account_only,Mobile_Money_Account_only,Both_Accounts
210,South Africa,ZAF,2011,53.65,NaN,NaN,NaN,33.97,8646.06,120.77,10.00,NaN,62.85,53.65,NaN,0.00,NaN
211,South Africa,ZAF,2014,70.32,NaN,52.70,14.43,49.00,6856.73,142.60,10.65,46.7,63.14,68.77,55.89,1.55,12.88
212,South Africa,ZAF,2017,69.22,NaN,43.08,19.02,56.17,6618.34,153.55,10.38,NaN,63.33,67.44,50.20,1.78,17.24
213,South Africa,ZAF,2021,85.38,NaN,70.16,36.57,74.97,6828.76,163.13,9.48,NaN,63.45,84.11,48.81,1.27,35.30
214,South Africa,ZAF,2022,NaN,NaN,NaN,NaN,78.29,6534.25,160.73,9.10,37.9,63.48,NaN,NaN,NaN,NaN

In [96]:
master.to_csv(
    "financial_inclusion_africa.csv",
    index=False
)

In [99]:
master['Country'].unique()

<StringArray>
[                  'Angola',                    'Benin',
                 'Botswana',             'Burkina Faso',
                  'Burundi',                 'Cameroon',
 'Central African Republic',                     'Chad',
                  'Comoros',         'Congo, Dem. Rep.',
              'Congo, Rep.',            'Cote d'Ivoire',
                 'Eswatini',                 'Ethiopia',
                    'Gabon',              'Gambia, The',
                    'Ghana',                   'Guinea',
                    'Kenya',                  'Lesotho',
                  'Liberia',                    'Libya',
               'Madagascar',                   'Malawi',
                     'Mali',               'Mauritania',
                'Mauritius',               'Mozambique',
                  'Namibia',                    'Niger',
                  'Nigeria',                   'Rwanda',
                  'Senegal',             'Sierra Leone',
                  'Somalia',             'South Africa',
              'South Sudan',                    'Sudan',
                 'Tanzania',                     'Togo',
                   'Uganda',                   'Zambia',
                 'Zimbabwe']
Length: 43, dtype: str