In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\ACCOUNT_OWNERSHIP,MOBILE_MONEY_ACCOUNT, DIGITAL_PAYMENTS.csv")
df_internet_users = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\INDIVIDUAL USING INTERNET (% OF POPULATION).csv"
,skiprows= 4)
df_GDP = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\GDP per CAPITA.csv"
,skiprows = 4)
df_Urban_Population = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\URBAN_POPULATION(% OF TOTAL POPULATION).csv",
skiprows = 4)
df_Poverty_Ratio = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\POVERTY HEAD COUNT RATIO AT NATIONAL POVERTY LINES.csv",
skiprows = 4)
df_Mobile_Subscription = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\MOBILE CELLULAR SUBSCRIPTION PER 100 PEOPLE.csv",
skiprows = 4)
df_Bank_Branches = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\WORLD DEVELOPMENT INDICATORS(WDI)\COMMERCIAL BRANCHES (per 100,000 adults).csv",
skiprows = 4)
df_bank_account = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\Bank_Account_financial_institution_account.csv")
df_mobile_money_impact =pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\FIndex_mobile _money_impact.csv")
df_comparison_indicators = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\Comparison_ indicators.csv")
df_comparison_2_indicators = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\comparison_2_indicators.csv")
df_comparison_3_indicators = pd.read_csv (r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\comparison_3_indicators.csv")
df_Population = pd.read_csv(r"C:\Users\hp\East Africa Financial Inclusion\Raw_Downloaded_Data\FINANCIAL INCLUSION (GLOBAL FINDEX)\Population age 15+.csv")

RENAMING THE YEARS in df

In [4]:
df_long = df.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_long.head(2)

,Country Name,Country Code,Series Name,Series Code,2011,2014,2017,2021,2022,2024
0,Angola,AGO,Account (% age 15+),account.t.d,39.2035423430619,29.3181213047365,..,..,..,..
1,Angola,AGO,Mobile money account (% age 15+),mobileaccount.t.d,..,..,..,..,..,..

CONVERTING YEARS INTO ONE COLUMN(MELT) in df_long

In [5]:
df_long = df_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

In [6]:
df_long.head(15)

,Country Name,Country Code,Series Name,Year,Value
0,Angola,AGO,Account (% age 15+),2011,39.2035423430619
1,Angola,AGO,Mobile money account (% age 15+),2011,..
2,Angola,AGO,Digitally enabled account (% age 15+),2011,..
3,Angola,AGO,Made a digital payment (% age 15+),2011,..
4,Benin,BEN,Account (% age 15+),2011,10.4639370332736
5,Benin,BEN,Mobile money account (% age 15+),2011,..
6,Benin,BEN,Digitally enabled account (% age 15+),2011,..
7,Benin,BEN,Made a digital payment (% age 15+),2011,..
8,Botswana,BWA,Account (% age 15+),2011,30.2600142850791
9,Botswana,BWA,Mobile money account (% age 15+),2011,..
10,Botswana,BWA,Digitally enabled account (% age 15+),2011,..
11,Botswana,BWA,Made a digital payment (% age 15+),2011,..
12,Burkina Faso,BFA,Account (% age 15+),2011,13.3530920184137
13,Burkina Faso,BFA,Mobile money account (% age 15+),2011,..
14,Burkina Faso,BFA,Digitally enabled account (% age 15+),2011,..

CHECKING FOR NAN VALUES IN IMPORTANT COLUMNS

In [7]:
df_long.loc[
    df_long[
        ["Country Name", "Country Code", "Series Name", "Value"]
    ].isna().any(axis=1),
    ["Country Name", "Country Code", "Series Name", "Value"]
]

,Country Name,Country Code,Series Name,Value
172,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN
174,NaN,NaN,NaN,NaN
175,Data from database: Global Findex database,NaN,NaN,NaN
176,Last Updated: 10/06/2025,NaN,NaN,NaN
349,NaN,NaN,NaN,NaN
350,NaN,NaN,NaN,NaN
351,NaN,NaN,NaN,NaN
352,Data from database: Global Findex database,NaN,NaN,NaN
353,Last Updated: 10/06/2025,NaN,NaN,NaN
526,NaN,NaN,NaN,NaN
527,NaN,NaN,NaN,NaN
528,NaN,NaN,NaN,NaN
529,Data from database: Global Findex database,NaN,NaN,NaN
530,Last Updated: 10/06/2025,NaN,NaN,NaN
703,NaN,NaN,NaN,NaN
704,NaN,NaN,NaN,NaN
705,NaN,NaN,NaN,NaN
706,Data from database: Global Findex database,NaN,NaN,NaN
707,Last Updated: 10/06/2025,NaN,NaN,NaN
880,NaN,NaN,NaN,NaN
881,NaN,NaN,NaN,NaN
882,NaN,NaN,NaN,NaN
883,Data from database: Global Findex database,NaN,NaN,NaN
884,Last Updated: 10/06/2025,NaN,NaN,NaN
1057,NaN,NaN,NaN,NaN
1058,NaN,NaN,NaN,NaN
1059,NaN,NaN,NaN,NaN
1060,Data from database: Global Findex database,NaN,NaN,NaN
1061,Last Updated: 10/06/2025,NaN,NaN,NaN

REMOVING NAN VALUES

In [8]:
df_long = df_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

MAKING SURE NAN VALUES ARE DROPPED

In [9]:
df_long.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Year            0
Value           0
dtype: int64

CREATING A PIVOT FOR (INDICATOR NAMES) TO APPEAR IN INDIVIDUAL COLUMNS

In [10]:
df_final = df_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_final.columns.name = None

df_final

,Country Name,Country Code,Year,Account (% age 15+),Digitally enabled account (% age 15+),Made a digital payment (% age 15+),Mobile money account (% age 15+)
0,Angola,AGO,2011,39.2035423430619,..,..,..
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..
2,Angola,AGO,2017,..,..,..,..
3,Angola,AGO,2021,..,..,..,..
4,Angola,AGO,2022,..,..,..,..
...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057
256,Zimbabwe,ZWE,2022,..,..,..,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992

RENAMING COLUMNS IN df_final

In [11]:
df_final = df_final.rename(columns = {
    'Country Name':'Country',
    'Country Code':'Code',
    'Account  (% age 15+)':'Account',
    'Digitally enabled account  (% age 15+)':'Digitally enabled Account',
    'Made a digital payment  (% age 15+)':'Made a Digital Payment',
    'Mobile money account  (% age 15+)':'Mobile Money Account'


})

df_final

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account
0,Angola,AGO,2011,39.2035423430619,..,..,..
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..
2,Angola,AGO,2017,..,..,..,..
3,Angola,AGO,2021,..,..,..,..
4,Angola,AGO,2022,..,..,..,..
...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057
256,Zimbabwe,ZWE,2022,..,..,..,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992

CLEANING (df_internet_users) DATAFRAME

In [12]:
year_cols = [col for col in df_internet_users.columns if col[:4].isdigit()]

df_internet_users_long = df_internet_users.melt(
    id_vars=["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name="Year",
    value_name="Value"
)

df_internet_users_long = df_internet_users_long[
    df_internet_users_long['Year'].isin(df_final['Year'].unique())
]

df_internet_users_long= df_internet_users_long[df_internet_users_long["Country Name"].isin(df_final['Country'].unique())]

df_internet_users_long = (df_internet_users_long.rename(columns={"Value":"Internet_users",'Country Name':'Country',
'Country Code': 'Code'})
                        .drop(columns = ['Indicator Name'])
                      )
df_internet_users_long[['Country','Code','Internet_users']].isna().sum()

Country            0
Code               0
Internet_users    11
dtype: int64

In [13]:
df_internet_users_long.loc[
    df_internet_users_long[
        ["Country", "Code", "Year", "Internet_users"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "Internet_users"]
]

                        Country Code  Year  Internet_users
13772                     Sudan  SDN  2011             NaN
13782               South Sudan  SSD  2011             NaN
14570                     Sudan  SDN  2014             NaN
15205          Congo, Dem. Rep.  COD  2017             NaN
16260  Central African Republic  CAF  2021             NaN
16432                     Sudan  SDN  2021             NaN
16442               South Sudan  SSD  2021             NaN
16698                     Sudan  SDN  2022             NaN
16708               South Sudan  SSD  2022             NaN
17230                     Sudan  SDN  2024             NaN
17240               South Sudan  SSD  2024             NaN

In [14]:
df_internet_users_long.duplicated(
    subset=["Country","Code","Year"]
).sum()

np.int64(0)

CLEANING GPD PER CAPITA DATASET

In [15]:
df_GDP_long = df_GDP.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_GDP_long = df_GDP_long[df_GDP_long['Year'].isin(df_final['Year'].unique())]
df_GDP_long = df_GDP_long[df_GDP_long['Country Name'].isin(df_final['Country'].unique())]

df_GDP_long = (df_GDP_long.rename(columns={"Value":"GDP",
'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_GDP_long

df_GDP_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

In [16]:
df_GDP_long.loc[
    df_GDP_long[
        ["Country", "Code", "Year", "GDP"]
    ].isna().any(axis=1),
    ["Country", "Code", "Year", "GDP"]
]

           Country Code  Year  GDP
15378  South Sudan  SSD  2017  NaN
16442  South Sudan  SSD  2021  NaN
16708  South Sudan  SSD  2022  NaN
17240  South Sudan  SSD  2024  NaN

CLEANING df_Urban_Population

In [17]:
df_Urban_Population_long= df_Urban_Population.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_Urban_Population_long= df_Urban_Population_long[df_Urban_Population_long['Year'].isin(df_final['Year'].unique())]
df_Urban_Population_long =df_Urban_Population_long[df_Urban_Population_long['Country Name'].isin(df_final['Country'].unique())]

df_Urban_Population_long = (df_Urban_Population_long.rename(columns={"Value":"Urban_population",'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_Urban_Population_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

CLEANING df_Povert_Ratio

In [18]:
df_poverty_ratio_long= df_Poverty_Ratio .melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_poverty_ratio_long= df_poverty_ratio_long[df_poverty_ratio_long['Year'].isin(df_final['Year'].unique())]
df_poverty_ratio_long =df_poverty_ratio_long[df_poverty_ratio_long['Country Name'].isin(df_final['Country'].unique())]

df_poverty_ratio_long = (df_poverty_ratio_long.rename(columns={"Value":"Poverty_ratio",'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))

df_poverty_ratio_long[['Country','Code']].isna().sum()

Country    0
Code       0
dtype: int64

CLEANING df_Mobile_Subscription

In [19]:
df_mobile_subscription_long= df_Mobile_Subscription.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_mobile_subscription_long= df_mobile_subscription_long[df_mobile_subscription_long['Year'].isin(df_final['Year'].unique())]
df_mobile_subscription_long =df_mobile_subscription_long[df_mobile_subscription_long['Country Name'].isin(df_final['Country'].unique())]

df_mobile_subscription_long = (df_mobile_subscription_long.rename(columns={"Value":"Mobile_cellular_subscription",'Country Name':'Country',
'Country Code': 'Code'})

                       .drop(columns=["Indicator Name"]))

df_mobile_subscription_long[['Country','Code','Mobile_cellular_subscription']].isna().sum()

Country                          0
Code                             0
Mobile_cellular_subscription    11
dtype: int64

CLEANING df_Bank_Branches

In [20]:
df_bank_branches_long= df_Bank_Branches.melt(
    id_vars= ["Country Name","Country Code","Indicator Name"],
    value_vars= year_cols,
    var_name='Year',
    value_name='Value'
)
df_bank_branches_long= df_bank_branches_long[df_bank_branches_long['Year'].isin(df_final['Year'].unique())]
df_bank_branches_long =df_bank_branches_long[df_bank_branches_long['Country Name'].isin(df_final['Country'].unique())]

df_bank_branches_long = (df_bank_branches_long.rename(columns={"Value":"Commercial_bank_branches",
'Country Name':'Country',
'Country Code': 'Code'})
                       .drop(columns=["Indicator Name"]))




df_bank_branches_long

df_bank_branches_long[['Country','Code']].isna().sum()

df_bank_branches_long

            Country Code  Year  Commercial_bank_branches
13570        Angola  AGO  2011                  8.144849
13582       Burundi  BDI  2011                  2.410982
13584         Benin  BEN  2011                  3.186366
13585  Burkina Faso  BFA  2011                  2.028757
13599      Botswana  BWA  2011                  8.320601
...             ...  ...   ...                       ...
17270      Tanzania  TZA  2024                       NaN
17271        Uganda  UGA  2024                       NaN
17287  South Africa  ZAF  2024                       NaN
17288        Zambia  ZMB  2024                       NaN
17289      Zimbabwe  ZWE  2024                       NaN

[252 rows x 4 columns]

CLEANING df_bank_account

In [21]:
df_bank_account_long = df_bank_account.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}
)
df_bank_account_long = df_bank_account_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)
df_bank_account_long = df_bank_account_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)
df_final_bank_account = df_bank_account_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_final_bank_account.columns.name = None

df_final_bank_account = df_final_bank_account.rename(columns = {
    'Country Name':'Country',
    'Country Code':'Code',
    'Bank or similar financial institution account  (% age 15+)':'Bank Account',
    
})

df_final_bank_account

      Country Code  Year      Bank Account
0      Angola  AGO  2011  39.2035423430619
1      Angola  AGO  2014  29.3181213047365
2      Angola  AGO  2017                ..
3      Angola  AGO  2021                ..
4      Angola  AGO  2022                ..
..        ...  ...   ...               ...
253  Zimbabwe  ZWE  2014  17.1894919246347
254  Zimbabwe  ZWE  2017  28.1799818696936
255  Zimbabwe  ZWE  2021  29.2496946936906
256  Zimbabwe  ZWE  2022                ..
257  Zimbabwe  ZWE  2024  21.5661530622998

[258 rows x 4 columns]

CHANGING DATA TYPE OF YEAR IN EVERY DATASET TO INT

In [22]:
for dataset in [df_final, 
df_internet_users_long, 
df_GDP_long, 
df_mobile_subscription_long, 
df_bank_branches_long,
df_poverty_ratio_long, 
df_Urban_Population_long,
df_final_bank_account]:
    dataset["Year"] = dataset["Year"].astype(int)

MERGING THE DATASETS

In [23]:
master = df_final.copy()

datasets = [
   df_internet_users_long, 
   df_GDP_long, 
   df_mobile_subscription_long,
   df_bank_branches_long,
   df_poverty_ratio_long, 
   df_Urban_Population_long,df_final_bank_account
  
]

for dataset in datasets:
    master = master.merge(
        dataset,
        on=["Country","Code","Year"],
        how="left"
    )

master

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,Mobile_cellular_subscription,Commercial_bank_branches,Poverty_ratio,Urban_population,Bank Account
0,Angola,AGO,2011,39.2035423430619,..,..,..,4.700000,5184.152691,49.851526,8.144849,NaN,60.843161,39.2035423430619
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..,21.362341,5649.687625,51.738439,10.018160,NaN,62.723116,29.3181213047365
2,Angola,AGO,2017,..,..,..,..,26.000000,2790.718869,44.068209,9.877548,NaN,65.085053,..
3,Angola,AGO,2021,..,..,..,..,34.556499,2303.908127,44.386869,8.035832,NaN,68.252416,..
4,Angola,AGO,2022,..,..,..,..,35.838001,3682.113151,66.600807,7.583594,NaN,69.050619,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691,16.364740,1372.915262,83.046061,14.668721,NaN,33.162808,17.1894919246347
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818,24.400000,3445.449410,95.136683,5.402445,30.4,34.701495,28.1799818696936
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057,32.592400,2613.605421,90.253849,5.818109,NaN,37.869206,29.2496946936906
256,Zimbabwe,ZWE,2022,..,..,..,..,36.256500,2536.400502,88.995831,5.542454,NaN,38.705521,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992,41.642799,2497.203322,94.245175,NaN,NaN,39.893372,21.5661530622998

In [24]:
print(master.columns.tolist())

['Country', 'Code', 'Year', 'Account', 'Digitally enabled Account', 'Made a Digital Payment', 'Mobile Money Account', 'Internet_users', 'GDP', 'Mobile_cellular_subscription', 'Commercial_bank_branches', 'Poverty_ratio', 'Urban_population', 'Bank Account']

In [25]:
master.to_csv(
    "financial_inclusion_africa.csv",
    index=False
)

RENAMING AND MELTING df_mobile_money_impact COLUMNS

In [26]:
df_mobile_impact_long = df_mobile_money_impact.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_mobile_impact_long = df_mobile_impact_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

df_mobile_impact_long = df_mobile_impact_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

df_mobile_impact_final= df_mobile_impact_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_mobile_impact_final.columns.name = None

df_mobile_impact_final

,Country Name,Country Code,Year,"Bank or similar financial institution account, men (% age 15+)","Bank or similar financial institution account, women (% age 15+)",Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),"Mobile money account, men (% age 15+)","Mobile money account, women (% age 15+)",Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),"Sent money from a mobile money account, less than once a month (% age 15+)","Sent or withdrew money from a bank or similar financial institution, monthly (%, age 15+) (% age 15+)","Sent or withdrew money from a mobile money account, Never (% age 15+) (% age 15+)"
0,Angola,AGO,2011,39.4809697161049,38.9283452528467,..,..,..,..,15.9155843112353,15.9155843112353,..,..,..,..
1,Angola,AGO,2014,36.1321313839668,22.3316464905364,5.65850260405293,5.65850260405293,..,..,14.860407234029,14.860407234029,..,..,..,..
2,Angola,AGO,2017,..,..,..,..,..,..,..,..,..,..,..,..
3,Angola,AGO,2021,..,..,..,..,..,..,..,..,..,..,..,..
4,Angola,AGO,2022,..,..,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,19.1269174459046,15.3363772170384,4.33172863312673,4.33172863312673,24.2077382836352,19.096979089115,5.19406162199756,5.19406162199756,..,..,..,..
254,Zimbabwe,ZWE,2017,33.4506396079702,23.3400166189628,4.72400367024086,4.72400367024086,51.1731724947713,46.2018599218938,5.31123850463518,5.31123850463518,..,..,..,..
255,Zimbabwe,ZWE,2021,34.9182502735752,23.9010269223203,7.22621971972311,2.88644347326737,55.6487640483814,45.8992056471716,4.08851771951058,12.0305118636693,9.42062503290648,..,..,..
256,Zimbabwe,ZWE,2022,..,..,..,..,..,..,..,..,..,..,..,..
257,Zimbabwe,ZWE,2024,24.4630545368656,19.0235024295338,6.34146240265946,2.90825624530331,47.1589137171279,39.9725706383566,3.30636176065889,13.6924551921877,12.5611572063273,23.2237045232041,9.75472463244777,4.57768742736453

In [27]:
df_mobile_impact_final=df_mobile_impact_final.rename(columns = 
                              {
                                  'Bank or similar financial institution account, men (% age 15+)':'Bank account,men',
                                  'Bank or similar financial institution account, women (% age 15+)':'Bank account, women',
                                  'Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)':'Borrowed any money from a formal bank or using a mobile money account',
                                  'Borrowed from a formal bank or similar financial institution  (% age 15+)':'Borrowed from a formal bank',
                                  'Mobile money account, men (% age 15+)':'Mobile money account, men',
                                  'Mobile money account, women (% age 15+)':'Mobile money account, women',
                                  'Saved at a bank or similar financial institution  (% age 15+)':'Saved at a bank',
                                  'Sent money from a mobile money account, less than once a month  (% age 15+)':'Sent money from a mobile money account, less than once a month',
                                  'Sent or withdrew money from a bank or similar financial institution, monthly (%,  age 15+) (% age 15+)':'Sent or withdrew money from a bank, monthly',
                                  'Sent or withdrew money from a mobile money account, Never (%  age 15+) (% age 15+)':'Sent or withdrew money from a mobile money account, Never',
                                  'Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)':'Saved at a bank or using a mobile money account',
                                
                                  'Saved money using a mobile money account  (% age 15+)':'Saved money using a mobile money account',
                                  'Country Name':'Country',
                                  'Country Code':'Code'
                              })



df_mobile_impact_final

,Country,Code,Year,"Bank account,men","Bank account, women",Borrowed any money from a formal bank or using a mobile money account,Borrowed from a formal bank,"Mobile money account, men","Mobile money account, women",Saved at a bank,Saved at a bank or using a mobile money account,Saved money using a mobile money account,"Sent money from a mobile money account, less than once a month","Sent or withdrew money from a bank, monthly","Sent or withdrew money from a mobile money account, Never"
0,Angola,AGO,2011,39.4809697161049,38.9283452528467,..,..,..,..,15.9155843112353,15.9155843112353,..,..,..,..
1,Angola,AGO,2014,36.1321313839668,22.3316464905364,5.65850260405293,5.65850260405293,..,..,14.860407234029,14.860407234029,..,..,..,..
2,Angola,AGO,2017,..,..,..,..,..,..,..,..,..,..,..,..
3,Angola,AGO,2021,..,..,..,..,..,..,..,..,..,..,..,..
4,Angola,AGO,2022,..,..,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,19.1269174459046,15.3363772170384,4.33172863312673,4.33172863312673,24.2077382836352,19.096979089115,5.19406162199756,5.19406162199756,..,..,..,..
254,Zimbabwe,ZWE,2017,33.4506396079702,23.3400166189628,4.72400367024086,4.72400367024086,51.1731724947713,46.2018599218938,5.31123850463518,5.31123850463518,..,..,..,..
255,Zimbabwe,ZWE,2021,34.9182502735752,23.9010269223203,7.22621971972311,2.88644347326737,55.6487640483814,45.8992056471716,4.08851771951058,12.0305118636693,9.42062503290648,..,..,..
256,Zimbabwe,ZWE,2022,..,..,..,..,..,..,..,..,..,..,..,..
257,Zimbabwe,ZWE,2024,24.4630545368656,19.0235024295338,6.34146240265946,2.90825624530331,47.1589137171279,39.9725706383566,3.30636176065889,13.6924551921877,12.5611572063273,23.2237045232041,9.75472463244777,4.57768742736453

RENAMING, MELTING AND PIVOTING df_comparison_indicators  COLUMNS

In [28]:
df_comparison_indicators_long = df_comparison_indicators.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_comparison_indicators_long = df_comparison_indicators_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

df_comparison_indicators_long = df_comparison_indicators_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)    

df_comparison_indicators_final= df_comparison_indicators_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_comparison_indicators_final.columns.name = None

df_comparison_indicators_final

,Country Name,Country Code,Year,"Bank or similar financial institution account, men (% age 15+)","Bank or similar financial institution account, women (% age 15+)",Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),"Mobile money account, men (% age 15+)","Mobile money account, women (% age 15+)",Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),"Sent money from a mobile money account, less than once a month (% age 15+)","Sent or withdrew money from a bank or similar financial institution, monthly (%, age 15+) (% age 15+)","Sent or withdrew money from a mobile money account, Never (% age 15+) (% age 15+)"
0,Angola,AGO,2011,39.4809697161049,38.9283452528467,..,..,..,..,15.9155843112353,15.9155843112353,..,..,..,..
1,Angola,AGO,2014,36.1321313839668,22.3316464905364,5.65850260405293,5.65850260405293,..,..,14.860407234029,14.860407234029,..,..,..,..
2,Angola,AGO,2017,..,..,..,..,..,..,..,..,..,..,..,..
3,Angola,AGO,2021,..,..,..,..,..,..,..,..,..,..,..,..
4,Angola,AGO,2022,..,..,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,19.1269174459046,15.3363772170384,4.33172863312673,4.33172863312673,24.2077382836352,19.096979089115,5.19406162199756,5.19406162199756,..,..,..,..
254,Zimbabwe,ZWE,2017,33.4506396079702,23.3400166189628,4.72400367024086,4.72400367024086,51.1731724947713,46.2018599218938,5.31123850463518,5.31123850463518,..,..,..,..
255,Zimbabwe,ZWE,2021,34.9182502735752,23.9010269223203,7.22621971972311,2.88644347326737,55.6487640483814,45.8992056471716,4.08851771951058,12.0305118636693,9.42062503290648,..,..,..
256,Zimbabwe,ZWE,2022,..,..,..,..,..,..,..,..,..,..,..,..
257,Zimbabwe,ZWE,2024,24.4630545368656,19.0235024295338,6.34146240265946,2.90825624530331,47.1589137171279,39.9725706383566,3.30636176065889,13.6924551921877,12.5611572063273,23.2237045232041,9.75472463244777,4.57768742736453

RENAMING, MELTING AND PIVOTING df_comparison_2_indicators  COLUMNS

In [29]:
df_comparison_2_indicators_long = df_comparison_2_indicators.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_comparison_2_indicators_long = df_comparison_2_indicators_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

df_comparison_2_indicators_long = df_comparison_2_indicators_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

df_comparison_2_indicators_final= df_comparison_2_indicators_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_comparison_2_indicators_final.columns.name = None

df_comparison_2_indicators_final

,Country Name,Country Code,Year,Borrowed from a mobile money provider (% age 15+),Received government payments (% age 15+),"Received government payments: in cash only (% of government payment recipients, age 15+)","Received government payments: into a bank or similar financial institution account (% of government payment recipients, age 15+)","Received government payments: into an account (% of government payment recipients, age 15+)","Received government payments: through a mobile phone (% of government payment recipients, age 15+)","Received government payments: to a card (% of government payment recipients, age 15+)",Received private sector wages (% age 15+),"Received private sector wages: in cash only (% of private sector wage recipients, age 15+)","Received private sector wages: into a bank or similar financial institution account (% of private sector wage recipients, age 15+)","Received private sector wages: into an account (% of private sector wage recipients, age 15+)","Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)","Received private sector wages: to a card (% of private sector wage recipients, age 15+)",Saved any money (% age 15+)
0,Angola,AGO,2011,..,..,..,..,..,..,..,..,..,..,..,..,..,..
1,Angola,AGO,2014,..,..,..,..,..,..,..,5.80599216139339,..,..,..,..,..,53.0579030355254
2,Angola,AGO,2017,..,..,..,..,..,..,..,..,..,..,..,..,..,..
3,Angola,AGO,2021,..,..,..,..,..,..,..,..,..,..,..,..,..,..
4,Angola,AGO,2022,..,..,..,..,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,..,..,..,..,..,..,..,11.6973443340501,..,..,..,..,..,51.9738827541939
254,Zimbabwe,ZWE,2017,..,15.7328171904095,..,..,..,..,..,19.2480019703893,..,..,52.7015861064598,..,..,53.594004254507
255,Zimbabwe,ZWE,2021,5.34296429646318,14.5504682832241,..,..,..,..,..,19.000206941768,..,..,..,..,..,51.9546493438954
256,Zimbabwe,ZWE,2022,..,..,..,..,..,..,..,..,..,..,..,..,..,..
257,Zimbabwe,ZWE,2024,4.37334297387324,15.7227330132043,..,..,..,..,..,18.1639053778212,58.0868469344542,..,..,..,..,45.8511336692934

RENAMING, MELTING AND PIVOTING df_comparison_3_indicators  COLUMNS

In [30]:
df_comparison_3_indicators_long = df_comparison_3_indicators.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_comparison_3_indicators_long = df_comparison_3_indicators_long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

df_comparison_3_indicators_long = df_comparison_3_indicators_long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

df_comparison_3_indicators_final= df_comparison_3_indicators_long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_comparison_3_indicators_final.columns.name = None

df_comparison_3_indicators_final

,Country Name,Country Code,Year,"Received payments for agricultural products: in cash only (% of agricultural payment recipients, age 15+)","Received payments for agricultural products: into an account (% of agricultural payment recipients, age 15+)","Received payments for agricultural products: through a mobile phone (% payment recipients, age 15+)"
0,Angola,AGO,2011,..,..,..
1,Angola,AGO,2014,94.7333777707823,..,..
2,Angola,AGO,2017,..,..,..
3,Angola,AGO,2021,..,..,..
4,Angola,AGO,2022,..,..,..
...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,83.3834891245499,..,..
254,Zimbabwe,ZWE,2017,71.7879592653703,..,..
255,Zimbabwe,ZWE,2021,..,..,..
256,Zimbabwe,ZWE,2022,..,..,..
257,Zimbabwe,ZWE,2024,61.5445379098466,..,..

In [31]:
for dataset in [
df_mobile_impact_final,df_comparison_2_indicators_final,
df_comparison_3_indicators_final,df_comparison_indicators_final]:
    dataset["Year"] = dataset["Year"].astype(int)

In [32]:
for dataset in [df_comparison_3_indicators_final,df_comparison_2_indicators_final,df_comparison_indicators_final]:
   dataset.rename(columns = {"Country Name": "Country",
                         "Country Code": "Code"},inplace=True)

In [33]:

df_Population_Long = df_Population.rename(columns={
    '2011 [YR2011]':'2011',
    '2014 [YR2014]':'2014',
    '2017 [YR2017]':'2017',
    '2021 [YR2021]':'2021',
    '2022 [YR2022]':'2022',
    '2024 [YR2024]':'2024'
}#, inplace = True)
)

df_Population_Long = df_Population_Long.melt(
    id_vars=["Country Name","Country Code","Series Name"],
    value_vars=["2011","2014","2017","2021","2022","2024"],
    var_name="Year",
    value_name="Value"
)

df_Population_Long = df_Population_Long.dropna(
    subset=["Country Name", "Country Code", "Series Name"]
)

df_Population_final= df_Population_Long.pivot(
    index=["Country Name","Country Code","Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_Population_final.columns.name = None
df_Population_final

,Country Name,Country Code,Year,"Population ages 0-14, total","Population, total"
0,Angola,AGO,2011,10934479.0,24218352.0
1,Angola,AGO,2014,12283698.0,27160769.0
2,Angola,AGO,2017,13681515.0,30234839.0
3,Angola,AGO,2021,15508255.0,34532429.0
4,Angola,AGO,2022,15949482.0,35635029.0
...,...,...,...,...,...
283,Zimbabwe,ZWE,2014,6241514.0,14207359.0
284,Zimbabwe,ZWE,2017,6411245.0,14812482.0
285,Zimbabwe,ZWE,2021,6614596.0,15797210.0
286,Zimbabwe,ZWE,2022,6686582.0,16069056.0
287,Zimbabwe,ZWE,2024,6799094.0,16634373.0

FINDING THE ADULT POPULATION

In [34]:
df_Population_final["Population_adult"] = df_Population_final["Population, total"]-df_Population_final["Population ages 0-14, total"]


df_Population_final= df_Population_final.drop(columns=["Population ages 0-14, total","Population, total"])

df_Population_final= df_Population_final.rename(columns = {
    "Country Name":"Country",
    "Country Code":"Code"
}
)

df_Population_final["Year"] = df_Population_final["Year"].astype(int)

df_Population_final

      Country Code  Year  Population_adult
0      Angola  AGO  2011        13283873.0
1      Angola  AGO  2014        14877071.0
2      Angola  AGO  2017        16553324.0
3      Angola  AGO  2021        19024174.0
4      Angola  AGO  2022        19685547.0
..        ...  ...   ...               ...
283  Zimbabwe  ZWE  2014         7965845.0
284  Zimbabwe  ZWE  2017         8401237.0
285  Zimbabwe  ZWE  2021         9182614.0
286  Zimbabwe  ZWE  2022         9382474.0
287  Zimbabwe  ZWE  2024         9835279.0

[288 rows x 4 columns]

In [35]:
master

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,Mobile_cellular_subscription,Commercial_bank_branches,Poverty_ratio,Urban_population,Bank Account
0,Angola,AGO,2011,39.2035423430619,..,..,..,4.700000,5184.152691,49.851526,8.144849,NaN,60.843161,39.2035423430619
1,Angola,AGO,2014,29.3181213047365,..,19.1783594962751,..,21.362341,5649.687625,51.738439,10.018160,NaN,62.723116,29.3181213047365
2,Angola,AGO,2017,..,..,..,..,26.000000,2790.718869,44.068209,9.877548,NaN,65.085053,..
3,Angola,AGO,2021,..,..,..,..,34.556499,2303.908127,44.386869,8.035832,NaN,68.252416,..
4,Angola,AGO,2022,..,..,..,..,35.838001,3682.113151,66.600807,7.583594,NaN,69.050619,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.3892493998773,..,27.6332251706875,21.5955208426691,16.364740,1372.915262,83.046061,14.668721,NaN,33.162808,17.1894919246347
254,Zimbabwe,ZWE,2017,55.2851376051058,..,49.2026128855119,48.5816321801818,24.400000,3445.449410,95.136683,5.402445,30.4,34.701495,28.1799818696936
255,Zimbabwe,ZWE,2021,59.7459292908934,..,53.7114226196222,50.6324444264057,32.592400,2613.605421,90.253849,5.818109,NaN,37.869206,29.2496946936906
256,Zimbabwe,ZWE,2022,..,..,..,..,36.256500,2536.400502,88.995831,5.542454,NaN,38.705521,..
257,Zimbabwe,ZWE,2024,49.5216018025126,46.5431857741491,42.5966496047633,43.3317368740992,41.642799,2497.203322,94.245175,NaN,NaN,39.893372,21.5661530622998

In [36]:
master[["Account", "Mobile Money Account", "Bank Account"]].dtypes

Account                 str
Mobile Money Account    str
Bank Account            str
dtype: object

PREPARING COLUMNS FOR CALCULATIONS

In [37]:
account_cols = ["Account", "Mobile Money Account", "Bank Account"]

for col in account_cols:
    master[col] = (
        master[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("%", "", regex=False)
        .str.strip()
    )
    master[col] = pd.to_numeric(master[col], errors="coerce")

In [38]:
master["Financial_Institution_Account_only"] = (
    master["Account"] - master["Mobile Money Account"]
)

master["Mobile_Money_Account_only"] = (
    master["Account"] - master["Bank Account"]
)

master["Both_Accounts"] = (
    master["Bank Account"] + master["Mobile Money Account"] - master["Account"]
)

In [39]:
master

,Country,Code,Year,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,Mobile_cellular_subscription,Commercial_bank_branches,Poverty_ratio,Urban_population,Bank Account,Financial_Institution_Account_only,Mobile_Money_Account_only,Both_Accounts
0,Angola,AGO,2011,39.203542,..,..,NaN,4.700000,5184.152691,49.851526,8.144849,NaN,60.843161,39.203542,NaN,0.000000,NaN
1,Angola,AGO,2014,29.318121,..,19.1783594962751,NaN,21.362341,5649.687625,51.738439,10.018160,NaN,62.723116,29.318121,NaN,0.000000,NaN
2,Angola,AGO,2017,NaN,..,..,NaN,26.000000,2790.718869,44.068209,9.877548,NaN,65.085053,NaN,NaN,NaN,NaN
3,Angola,AGO,2021,NaN,..,..,NaN,34.556499,2303.908127,44.386869,8.035832,NaN,68.252416,NaN,NaN,NaN,NaN
4,Angola,AGO,2022,NaN,..,..,NaN,35.838001,3682.113151,66.600807,7.583594,NaN,69.050619,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Zimbabwe,ZWE,2014,32.389249,..,27.6332251706875,21.595521,16.364740,1372.915262,83.046061,14.668721,NaN,33.162808,17.189492,10.793729,15.199757,6.395763
254,Zimbabwe,ZWE,2017,55.285138,..,49.2026128855119,48.581632,24.400000,3445.449410,95.136683,5.402445,30.4,34.701495,28.179982,6.703505,27.105156,21.476476
255,Zimbabwe,ZWE,2021,59.745929,..,53.7114226196222,50.632444,32.592400,2613.605421,90.253849,5.818109,NaN,37.869206,29.249695,9.113485,30.496235,20.136210
256,Zimbabwe,ZWE,2022,NaN,..,..,NaN,36.256500,2536.400502,88.995831,5.542454,NaN,38.705521,NaN,NaN,NaN,NaN
257,Zimbabwe,ZWE,2024,49.521602,46.5431857741491,42.5966496047633,43.331737,41.642799,2497.203322,94.245175,NaN,NaN,39.893372,21.566153,6.189865,27.955449,15.376288

In [40]:
new_datasets = [
    df_comparison_2_indicators_final,
    df_comparison_3_indicators_final,
    df_comparison_indicators_final,
    df_Population_final
]

for dataset in new_datasets:
    master = master.merge(
        dataset,
        on=["Country", "Code", "Year"],
        how="left"
    )

In [41]:
print(master.columns)

Index(['Country', 'Code', 'Year', 'Account', 'Digitally enabled Account',
       'Made a Digital Payment', 'Mobile Money Account', 'Internet_users',
       'GDP', 'Mobile_cellular_subscription', 'Commercial_bank_branches',
       'Poverty_ratio', 'Urban_population', 'Bank Account',
       'Financial_Institution_Account_only', 'Mobile_Money_Account_only',
       'Both_Accounts', 'Borrowed from a mobile money provider  (% age 15+)',
       'Received government payments  (% age 15+)',
       'Received government payments: in cash only (% of government payment recipients, age 15+)',
       'Received government payments: into a bank or similar financial institution account (% of government payment recipients, age 15+)',
       'Received government payments: into an account (% of government payment recipients, age 15+)',
       'Received government payments: through a mobile phone (% of government payment recipients, age 15+)',
       'Received government payments: to a card (% of government payment recipients, age 15+)',
       'Received private sector wages  (% age 15+)',
       'Received private sector wages: in cash only (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into a bank or similar financial institution account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into an account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)',
       'Received private sector wages: to a card (% of private sector wage recipients, age 15+)',
       'Saved any money  (% age 15+)',
       'Received payments for agricultural products: in cash only (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: into an account (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: through a mobile phone (% payment recipients, age 15+)',
       'Bank or similar financial institution account, men (% age 15+)',
       'Bank or similar financial institution account, women (% age 15+)',
       'Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Borrowed from a formal bank or similar financial institution  (% age 15+)',
       'Mobile money account, men (% age 15+)',
       'Mobile money account, women (% age 15+)',
       'Saved at a bank or similar financial institution  (% age 15+)',
       'Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Saved money using a mobile money account  (% age 15+)',
       'Sent money from a mobile money account, less than once a month  (% age 15+)',
       'Sent or withdrew money from a bank or similar financial institution, monthly (%,  age 15+) (% age 15+)',
       'Sent or withdrew money from a mobile money account, Never (%  age 15+) (% age 15+)',
       'Population_adult'],
      dtype='str')

In [42]:
master.to_csv("financial_inclusion_africa.csv", index=False)