In [1]:
import pandas as pd

master = pd.read_csv(r"C:\Users\hp\EAST AFRICA FINANCIAL INCLUSION\Cleaned_Merged_Data\financial_inclusion_africa.csv")

In [2]:
df_financial_inclusion_Kenya  = master.loc[
    (master["Year"].isin([2021, 2024,2014])) &
    (master["Country"] == "Kenya"),
    [
        "Year",
        "Account",
        "Financial_Institution_Account_only",
        "Mobile_Money_Account_only",
        "Both_Accounts",
        "Mobile Money Account",
        "Bank Account",
    ],
]

df_financial_inclusion_Kenya.to_csv("financial_inclusion_Kenya_2014-2024.csv", index = False)

creating a dataframe showing each column as  % of savers in kenya(2021)

In [3]:
import pandas as pd

# 1. Create the DataFrame using your exact column names
data = {
    "Year": [2021],
    "Saved any money  (% age 15+)": [66.7671320369555],
    "Saved at a bank or similar financial institution  (% age 15+)": [21.4531739032776],
    "Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)": [45.0110991275483],
    "Saved money using a mobile money account  (% age 15+)": [37.2453264493391]
}

df_savers_2021 = pd.DataFrame(data)

# 2. Extract values dynamically from the DataFrame columns
saved_any = df_savers_2021["Saved any money  (% age 15+)"]
saved_bank = df_savers_2021["Saved at a bank or similar financial institution  (% age 15+)"]
saved_formal_or_mobile = df_savers_2021["Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)"]
saved_mobile = df_savers_2021["Saved money using a mobile money account  (% age 15+)"]

# 3. Calculate underlying population overlaps (% of total population)
pop_both = saved_bank + saved_mobile - saved_formal_or_mobile
pop_mobile_only = saved_mobile - pop_both
pop_bank_only = saved_bank - pop_both
pop_informal_only = saved_any - saved_formal_or_mobile

# 4. Append the new calculations back as new columns scaled to the % of savers
df_savers_2021["Mobile Money ONLY (% of savers)"] = (pop_mobile_only / saved_any) * 100
df_savers_2021["Informal ONLY (% of savers)"] = (pop_informal_only / saved_any) * 100
df_savers_2021["Both Accounts (% of savers)"] = (pop_both / saved_any) * 100
df_savers_2021["Traditional Bank ONLY (% of savers)"] = (pop_bank_only / saved_any) * 100

df_savers_2021

,Year,Saved any money (% age 15+),Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),Mobile Money ONLY (% of savers),Informal ONLY (% of savers),Both Accounts (% of savers),Traditional Bank ONLY (% of savers)
0,2021,66.767132,21.453174,45.011099,37.245326,35.283716,32.584944,20.500208,11.631131

creating a dataframe showing each column as  % of savers in kenya(2024)

In [4]:
import pandas as pd

# 1. Create the 2024 DataFrame using unique column names to avoid clashing
df_savers_2024 = {
    "Year":[2024],
    "Saved any money  (% age 15+)": [70.1941670327483],
    "Saved at a bank or similar financial institution  (% age 15+)": [20.1488814386545],
    "Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)": [54.4225878392456],
    "Saved money using a mobile money account  (% age 15+)": [50.4706093324556]
}

df_2024 = pd.DataFrame(df_savers_2024)

# 2. Extract values dynamically from the 2024 columns
saved_any_24 = df_2024["Saved any money  (% age 15+)"]
saved_bank_24 = df_2024["Saved at a bank or similar financial institution  (% age 15+)"]
saved_formal_or_mobile_24 = df_2024["Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)"]
saved_mobile_24 = df_2024["Saved money using a mobile money account  (% age 15+)"]

# 3. Calculate underlying population overlaps for 2024
pop_both_24 = saved_bank_24 + saved_mobile_24 - saved_formal_or_mobile_24
pop_mobile_only_24 = saved_mobile_24 - pop_both_24
pop_bank_only_24 = saved_bank_24 - pop_both_24
pop_informal_only_24 = saved_any_24 - saved_formal_or_mobile_24

# 4. Append the calculations using distinctive 2024 column names
df_2024["Mobile Money ONLY (% of 2024 savers)"] = (pop_mobile_only_24 / saved_any_24) * 100
df_2024["Informal ONLY (% of 2024 savers)"] = (pop_informal_only_24 / saved_any_24) * 100
df_2024["Both Accounts (% of 2024 savers)"] = (pop_both_24 / saved_any_24) * 100
df_2024["Traditional Bank ONLY (% of 2024 savers)"] = (pop_bank_only_24 / saved_any_24) * 100

# Display the 2024 DataFrame
df_2024

,Year,Saved any money (% age 15+),Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),Mobile Money ONLY (% of 2024 savers),Informal ONLY (% of 2024 savers),Both Accounts (% of 2024 savers),Traditional Bank ONLY (% of 2024 savers)
0,2024,70.194167,20.148881,54.422588,50.470609,48.827001,22.468504,23.074429,5.630067

creating a dataframe showing each column as  % of borrowers in kenya(2021)

In [5]:
import pandas as pd

# 1. Create the DataFrame and inject the missing 76.01% global indicator column
data_borrow_2021 = {
    "Year":[2021],
    "Borrowed any money  (% age 15+)": [76.01],  # Added baseline column
    "Borrowed from a mobile money provider  (% age 15+)": [29.6369870123126],
    "Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)": [39.6867384230357],
    "Borrowed from a formal bank or similar financial institution  (% age 15+)": [22.1745117338]
}

df_borrowers_2021 = pd.DataFrame(data_borrow_2021)

# 2. Extract active columns dynamically using unique 2021 borrow variable names
any_borrow_21 = df_borrowers_2021["Borrowed any money  (% age 15+)"]
mobile_borrow_21 = df_borrowers_2021["Borrowed from a mobile money provider  (% age 15+)"]
formal_mobile_borrow_21 = df_borrowers_2021["Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)"]
bank_borrow_21 = df_borrowers_2021["Borrowed from a formal bank or similar financial institution  (% age 15+)"]

# 3. Calculate underlying population splits with unique formula variable names
both_accounts_pop_21 = bank_borrow_21 + mobile_borrow_21 - formal_mobile_borrow_21
mobile_only_pop_21 = mobile_borrow_21 - both_accounts_pop_21
bank_only_pop_21 = bank_borrow_21 - both_accounts_pop_21
informal_only_pop_21 = any_borrow_21 - formal_mobile_borrow_21

# 4. Save calculations as new columns with distinct 2021 borrower labels
df_borrowers_2021["Informal ONLY (% of 2021 borrowers)"] = (informal_only_pop_21 / any_borrow_21) * 100
df_borrowers_2021["Mobile Money ONLY (% of 2021 borrowers)"] = (mobile_only_pop_21 / any_borrow_21) * 100
df_borrowers_2021["Both Accounts (% of 2021 borrowers)"] = (both_accounts_pop_21 / any_borrow_21) * 100
df_borrowers_2021["Traditional Bank ONLY (% of 2021 borrowers)"] = (bank_only_pop_21 / any_borrow_21) * 100

# 5. Display the final uniquely named dataset columns 
df_borrowers_2021

,Year,Borrowed any money (% age 15+),Borrowed from a mobile money provider (% age 15+),Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),Informal ONLY (% of 2021 borrowers),Mobile Money ONLY (% of 2021 borrowers),Both Accounts (% of 2021 borrowers),Traditional Bank ONLY (% of 2021 borrowers)
0,2021,76.01,29.636987,39.686738,22.174512,47.787477,23.039372,15.951533,13.221617

borroers 2021

In [6]:

# 1. Store your 2021 borrowing row and manually inject the 76.01 baseline column
data_borrow_2021 = {
    "Year":[2021],
    "Borrowed any money  (% age 15+)": [76.01],  # Added global indicator column
    "Borrowed from a mobile money provider  (% age 15+)": [29.6369870123126],
    "Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)": [39.6867384230357],
    "Borrowed from a formal bank or similar financial institution  (% age 15+)": [22.1745117338]
}

df_borrowersK_2021 = pd.DataFrame(data_borrow_2021)

# 2. Extract values dynamically into uniquely named population variables
total_borrow_pop_21 = df_borrowersK_2021["Borrowed any money  (% age 15+)"]
mobile_borrow_pop_21 = df_borrowersK_2021["Borrowed from a mobile money provider  (% age 15+)"]
formal_mobile_borrow_pop_21 = df_borrowersK_2021["Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)"]
bank_borrow_pop_21 = df_borrowersK_2021["Borrowed from a formal bank or similar financial institution  (% age 15+)"]

# 3. Apply the math formula to keep metrics as % of total Kenyan population
both_accounts_pop_21 = bank_borrow_pop_21 + mobile_borrow_pop_21 - formal_mobile_borrow_pop_21
mobile_only_pop_21 = mobile_borrow_pop_21 - both_accounts_pop_21
bank_only_pop_21 = bank_borrow_pop_21 - both_accounts_pop_21

# Isolate informal lenders by subtracting formal borrowing from the 76.01 baseline
informal_only_pop_21 = total_borrow_pop_21 - formal_mobile_borrow_pop_21

# 4. Save calculations using short, clean column labels
df_borrowersK_2021["Informal ONLY"] = informal_only_pop_21
df_borrowersK_2021["Mobile Money ONLY"] = mobile_only_pop_21
df_borrowersK_2021["Both Accounts"] = both_accounts_pop_21
df_borrowersK_2021["Traditional Bank ONLY"] = bank_only_pop_21

df_borrowersK_2021

,Year,Borrowed any money (% age 15+),Borrowed from a mobile money provider (% age 15+),Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),Informal ONLY,Mobile Money ONLY,Both Accounts,Traditional Bank ONLY
0,2021,76.01,29.636987,39.686738,22.174512,36.323262,17.512227,12.12476,10.049751

borrowers 2024

In [7]:

# 1. Store your correct 2024 borrowing data row and inject the 74.90% baseline
data_2024 = {
    "Year": [2024],
    "Borrowed any money  (% age 15+)": [74.90],  # Total population borrowing benchmark
    "Borrowed from a mobile money provider  (% age 15+)": [32.3654073107561],
    "Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)": [37.5464332767464],
    "Borrowed from a formal bank or similar financial institution  (% age 15+)": [12.6129604153793]
}

df_borrowers_2024 = pd.DataFrame(data_2024)

# 2. Extract values dynamically using unique 2024 variable tags
any_borrow_24 = df_borrowers_2024["Borrowed any money  (% age 15+)"]
mobile_borrow_24 = df_borrowers_2024["Borrowed from a mobile money provider  (% age 15+)"]
formal_mobile_borrow_24 = df_borrowers_2024["Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)"]
bank_borrow_24 = df_borrowers_2024["Borrowed from a formal bank or similar financial institution  (% age 15+)"]

# 3. Apply the inclusion-exclusion principle for raw population shares
both_accounts_pop_24 = bank_borrow_24 + mobile_borrow_24 - formal_mobile_borrow_24
mobile_only_pop_24 = mobile_borrow_24 - both_accounts_pop_24
bank_only_pop_24 = bank_borrow_24 - both_accounts_pop_24

# Subtract formal credit options from the 74.90% baseline to find informal only
informal_only_pop_24 = any_borrow_24 - formal_mobile_borrow_24

# 4. Save calculations back to the DataFrame using short, clean names
df_borrowers_2024["Informal ONLY"] = informal_only_pop_24
df_borrowers_2024["Mobile Money ONLY"] = mobile_only_pop_24
df_borrowers_2024["Both Accounts"] = both_accounts_pop_24
df_borrowers_2024["Traditional Bank ONLY"] = bank_only_pop_24

df_borrowers_2024

,Year,Borrowed any money (% age 15+),Borrowed from a mobile money provider (% age 15+),Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),Informal ONLY,Mobile Money ONLY,Both Accounts,Traditional Bank ONLY
0,2024,74.9,32.365407,37.546433,12.61296,37.353567,24.933473,7.431934,5.181026

savers 2021

borrowers 2021 and 2024

In [8]:
# Pass both borrowing rows together
dict_borrow_master = {
    "Year":[2021,2024],
    "Borrowed any money  (% age 15+)": [76.01, 74.90],  # Combined indicators
    "Borrowed from a mobile money provider  (% age 15+)": [29.6369870123126, 32.3654073107561],
    "Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)": [39.6867384230357, 37.5464332767464],
    "Borrowed from a formal bank or similar financial institution  (% age 15+)": [22.1745117338, 12.6129604153793]
}

df_borrowing = pd.DataFrame(dict_borrow_master)

borrowed_any = df_borrowing["Borrowed any money  (% age 15+)"]
borrowed_mobile = df_borrowing["Borrowed from a mobile money provider  (% age 15+)"]
borrowed_formal_or_mobile = df_borrowing["Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)"]
borrowed_bank = df_borrowing["Borrowed from a formal bank or similar financial institution  (% age 15+)"]

both_accounts = borrowed_bank + borrowed_mobile - borrowed_formal_or_mobile

df_borrowing["Informal ONLY"] = (borrowed_any - borrowed_formal_or_mobile).round(2)
df_borrowing["Mobile Money ONLY"] = (borrowed_mobile - both_accounts).round(2)
df_borrowing["Both Accounts"] = both_accounts.round(2)
df_borrowing["Traditional Bank ONLY"] = (borrowed_bank - both_accounts).round(2)

df_borrowing



df_borrowing.to_csv("Borrowing_in_Kenya_2021-2024.csv", index=False)

In [9]:
import pandas as pd

# 1. Store your 2021 savings row using a distinct dictionary name
save_2021 = {
    "Year": [2021],
    "Saved any money  (% age 15+)": [66.7671320369555],
    "Saved at a bank or similar financial institution  (% age 15+)": [21.4531739032776],
    "Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)": [45.0110991275483],
    "Saved money using a mobile money account  (% age 15+)": [37.2453264493391]
}

df_savers_21 = pd.DataFrame(save_2021)

# 2. Extract values dynamically using isolated savings variables
any_save_s21 = df_savers_21["Saved any money  (% age 15+)"]
bank_save_s21 = df_savers_21["Saved at a bank or similar financial institution  (% age 15+)"]
formal_mobile_save_s21 = df_savers_21["Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)"]
mobile_save_s21 = df_savers_21["Saved money using a mobile money account  (% age 15+)"]

# 3. Calculate underlying population splits with unique math labels (Typo Fixed)
both_accounts_pop_s21 = bank_save_s21 + mobile_save_s21 - formal_mobile_save_s21
mobile_only_pop_s21 = mobile_save_s21 - both_accounts_pop_s21
bank_only_pop_s21 = bank_save_s21 - both_accounts_pop_s21
informal_only_pop_s21 = any_save_s21 - formal_mobile_save_s21

# 4. Save calculations back to the DataFrame using clean column names
df_savers_21["Informal ONLY"] = informal_only_pop_s21
df_savers_21["Mobile Money ONLY"] = mobile_only_pop_s21
df_savers_21["Both Accounts"] = both_accounts_pop_s21
df_savers_21["Traditional Bank ONLY"] = bank_only_pop_s21

df_savers_21

,Year,Saved any money (% age 15+),Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),Informal ONLY,Mobile Money ONLY,Both Accounts,Traditional Bank ONLY
0,2021,66.767132,21.453174,45.011099,37.245326,21.756033,23.557925,13.687401,7.765773

savers 2024

Savers 2021 and 2024

In [10]:

# Pass both years together as list rows inside the dictionary
dict_savings_master = {
    "Year":[2021,2024],
    "Saved any money  (% age 15+)": [66.7671320369555, 70.1941670327483],
    "Saved at a bank or similar financial institution  (% age 15+)": [21.4531739032776, 20.1488814386545],
    "Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)": [45.0110991275483, 54.4225878392456],
    "Saved money using a mobile money account  (% age 15+)": [37.2453264493391, 50.4706093324556]
}

df_savings = pd.DataFrame(dict_savings_master)

# Vectorized math runs on all rows simultaneously
saved_any = df_savings["Saved any money  (% age 15+)"]
saved_bank = df_savings["Saved at a bank or similar financial institution  (% age 15+)"]
saved_formal_or_mobile = df_savings["Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)"]
saved_mobile = df_savings["Saved money using a mobile money account  (% age 15+)"]

both_accounts = saved_bank + saved_mobile - saved_formal_or_mobile

# Create clean output columns (rounded to 2 decimal places for neatness)
df_savings["Informal ONLY"] = (saved_any - saved_formal_or_mobile).round(2)
df_savings["Mobile Money ONLY"] = (saved_mobile - both_accounts).round(2)
df_savings["Both Accounts"] = both_accounts.round(2)
df_savings["Traditional Bank ONLY"] = (saved_bank - both_accounts).round(2)

df_savings

df_savings.to_csv("Saving_in_Kenya_2021-2024.csv", index=False)

In [11]:


# 1. Store your 2024 savings row using a distinct dictionary name
save_2024 = {
    "Year":[2024],
    "Saved any money  (% age 15+)": [70.1941670327483],
    "Saved at a bank or similar financial institution  (% age 15+)": [20.1488814386545],
    "Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)": [54.4225878392456],
    "Saved money using a mobile money account  (% age 15+)": [50.4706093324556]
}

df_savers_2024 = pd.DataFrame(save_2024)

# 2. Extract values dynamically using isolated 2024 savings variables
any_save_s24 = df_savers_2024["Saved any money  (% age 15+)"]
bank_save_s24 = df_savers_2024["Saved at a bank or similar financial institution  (% age 15+)"]
formal_mobile_save_s24 = df_savers_2024["Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)"]
mobile_save_s24 = df_savers_2024["Saved money using a mobile money account  (% age 15+)"]

# 3. Calculate underlying population splits with unique 2024 math labels
both_accounts_pop_s24 = bank_save_s24 + mobile_save_s24 - formal_mobile_save_s24
mobile_only_pop_s24 = mobile_save_s24 - both_accounts_pop_s24
bank_only_pop_s24 = bank_save_s24 - both_accounts_pop_s24
informal_only_pop_s24 = any_save_s24 - formal_mobile_save_s24

# 4. Save calculations back to the DataFrame using clean, shared column names
df_savers_2024["Informal ONLY"] = informal_only_pop_s24
df_savers_2024["Mobile Money ONLY"] = mobile_only_pop_s24
df_savers_2024["Both Accounts"] = both_accounts_pop_s24
df_savers_2024["Traditional Bank ONLY"] = bank_only_pop_s24

df_savers_2024

,Year,Saved any money (% age 15+),Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),Informal ONLY,Mobile Money ONLY,Both Accounts,Traditional Bank ONLY
0,2024,70.194167,20.148881,54.422588,50.470609,15.771579,34.273706,16.196903,3.951979

Private sector wages

In [12]:
import pandas as pd

# 1. Store your 2024 row exactly as it is structured in the Global Findex
private_wages_2024 = {
    "Year": [2024],
    "Received private sector wages  (% age 15+)": [26.2883447955206],
    "Received private sector wages: into an account (% of private sector wage recipients, age 15+)": [81.1812050561477],
    "Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)": [70.7290405709424]
}

df_private_wages_2024 = pd.DataFrame(private_wages_2024)

# 2. Extract active columns dynamically using unique wage variable tags
wages_any_2024 = df_private_wages_2024["Received private sector wages  (% age 15+)"]
into_account_rate_2024 = df_private_wages_2024["Received private sector wages: into an account (% of private sector wage recipients, age 15+)"]
through_mobile_rate_2024 = df_private_wages_2024["Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)"]

# 3. Step 1: Scale the recipient ratios back into total population percentages
pop_into_account_2024 = (into_account_rate_2024 / 100.0) * wages_any_2024
pop_mobile_2024 = (through_mobile_rate_2024 / 100.0) * wages_any_2024

# 4. Step 2: Run subtractions against the master benchmarks to fill in the missing '..' data
# Since "into an account" includes ALL electronic methods, the remainder is Cash Only
pop_cash_only_2024 = wages_any_2024 - pop_into_account_2024

# Subtract mobile phone wages from total account wages to isolate pure Bank/Card options
pop_bank_or_card_only_2024 = pop_into_account_2024 - pop_mobile_2024

# 5. Save calculations back to the DataFrame using clean, shared column names
df_private_wages_2024["Cash ONLY"] = pop_cash_only_2024
df_private_wages_2024["Mobile Money / Phone"] = pop_mobile_2024
df_private_wages_2024["Traditional Bank or Card ONLY"] = pop_bank_or_card_only_2024


df_private_wages_2024

,Year,Received private sector wages (% age 15+),"Received private sector wages: into an account (% of private sector wage recipients, age 15+)","Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)",Cash ONLY,Mobile Money / Phone,Traditional Bank or Card ONLY
0,2024,26.288345,81.181205,70.729041,4.94715,18.593494,2.747701

private wages receiver 2021

In [13]:
# 1. Store your 2021 row exactly as it is structured in the Global Findex
wages_2021 = {
    "Year": [2021],
    "Received private sector wages  (% age 15+)": [24.1285199426547],
    "Received private sector wages: into an account (% of private sector wage recipients, age 15+)": [75.6136760486134],
    "Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)": [60.5440791246106]
}

df_private_wages_2021 = pd.DataFrame(wages_2021)

# 2. Extract active columns dynamically using isolated 2021 variables
wages_any_2021 = df_private_wages_2021["Received private sector wages  (% age 15+)"]
into_account_rate_2021 = df_private_wages_2021["Received private sector wages: into an account (% of private sector wage recipients, age 15+)"]
through_mobile_rate_2021 = df_private_wages_2021["Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)"]

# 3. Step 1: Multiply the rates to convert from "earners share" to "total population share"
pop_into_account_2021 = (into_account_rate_2021 / 100.0) * wages_any_2021
pop_mobile_2021 = (through_mobile_rate_2021 / 100.0) * wages_any_2021

# 4. Step 2: Use subtraction to fill in the missing ".." categories
# Any worker who didn't receive an electronic account payment was paid in cash
pop_cash_only_2021 = wages_any_2021 - pop_into_account_2021

# Subtract mobile recipients from total account recipients to isolate pure Bank/Card options
pop_bank_or_card_only_2021 = pop_into_account_2021 - pop_mobile_2021

# 5. Save calculations back to the DataFrame using clean, shared column names
df_private_wages_2021["Cash ONLY"] = pop_cash_only_2021
df_private_wages_2021["Mobile Money / Phone"] = pop_mobile_2021
df_private_wages_2021["Traditional Bank or Card ONLY"] = pop_bank_or_card_only_2021

df_private_wages_2021

,Year,Received private sector wages (% age 15+),"Received private sector wages: into an account (% of private sector wage recipients, age 15+)","Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)",Cash ONLY,Mobile Money / Phone,Traditional Bank or Card ONLY
0,2021,24.12852,75.613676,60.544079,5.884059,14.60839,3.636071

Received_wages

In [14]:
dict_wages = {
    "Year":[2021,2024],
    "Received private sector wages  (% age 15+)": [24.1285199426547, 26.2883447955206],
    "Received private sector wages: into an account (% of private sector wage recipients, age 15+)": [75.6136760486134, 81.1812050561477],
    "Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)": [60.5440791246106, 70.7290405709424]
}

df_wages = pd.DataFrame(dict_wages)

wages_any = df_wages["Received private sector wages  (% age 15+)"]
into_an_account = df_wages["Received private sector wages: into an account (% of private sector wage recipients, age 15+)"]
through_mobile_money = df_wages["Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)"]

# Scale recipient shares to whole population levels
into_an_account_oftotalpopulation = (into_an_account / 100.0) * wages_any
mobile_money_oftotalpopulation = (through_mobile_money / 100.0) * wages_any

df_wages["Cash ONLY"] = (wages_any - into_an_account_oftotalpopulation).round(2)
df_wages["Mobile Money / Phone"] = mobile_money_oftotalpopulation.round(2)
df_wages["Traditional Bank or Card ONLY"] = (into_an_account_oftotalpopulation - mobile_money_oftotalpopulation).round(2)

df_wages

df_wages.to_csv("Private_Sector_wages_in_Kenya_2021-2024.csv", index=False)