In [1]:
import pandas as pd
import numpy as np

master = pd.read_csv(r"C:\Users\hp\EAST AFRICA FINANCIAL INCLUSION\financial_inclusion_africa.csv")

In [2]:
print(master.columns)

Index(['Country', 'Code', 'Year', 'Account', 'Digitally enabled Account',
       'Made a Digital Payment', 'Mobile Money Account', 'Internet_users',
       'GDP', 'Mobile_cellular_subscription', 'Commercial_bank_branches',
       'Poverty_ratio', 'Urban_population', 'Bank Account',
       'Financial_Institution_Account_only', 'Mobile_Money_Account_only',
       'Both_Accounts', 'Borrowed from a mobile money provider  (% age 15+)',
       'Received government payments  (% age 15+)',
       'Received government payments: in cash only (% of government payment recipients, age 15+)',
       'Received government payments: into a bank or similar financial institution account (% of government payment recipients, age 15+)',
       'Received government payments: into an account (% of government payment recipients, age 15+)',
       'Received government payments: through a mobile phone (% of government payment recipients, age 15+)',
       'Received government payments: to a card (% of government payment recipients, age 15+)',
       'Received private sector wages  (% age 15+)',
       'Received private sector wages: in cash only (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into a bank or similar financial institution account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into an account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)',
       'Received private sector wages: to a card (% of private sector wage recipients, age 15+)',
       'Saved any money  (% age 15+)',
       'Received payments for agricultural products: in cash only (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: into an account (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: through a mobile phone (% payment recipients, age 15+)',
       'Bank or similar financial institution account, men (% age 15+)',
       'Bank or similar financial institution account, women (% age 15+)',
       'Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Borrowed from a formal bank or similar financial institution  (% age 15+)',
       'Mobile money account, men (% age 15+)',
       'Mobile money account, women (% age 15+)',
       'Saved at a bank or similar financial institution  (% age 15+)',
       'Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Saved money using a mobile money account  (% age 15+)',
       'Sent money from a mobile money account, less than once a month  (% age 15+)',
       'Sent or withdrew money from a bank or similar financial institution, monthly (%,  age 15+) (% age 15+)',
       'Sent or withdrew money from a mobile money account, Never (%  age 15+) (% age 15+)',
       'Population_adult'],
      dtype='str')

In [3]:

master["Population_adult"] = pd.to_numeric(master["Population_adult"], errors="coerce")

exclude_cols = ["Country", "Code", "Year", "Population_adult"]

indicator_cols = [
    col for col in master.columns
    if col not in exclude_cols
]

ssa_rows = []

for year, group in master.groupby("Year"):

    total_population = group["Population_adult"].sum(skipna=True)

    row = {
        "Region": "Sub-Saharan Africa",
        "Code": "SSA",
        "Year": year,
        "Population_adult": total_population
    }

    for col in indicator_cols:

        valid = group[[col, "Population_adult"]].copy()

        valid[col] = pd.to_numeric(valid[col], errors="coerce")
        valid["Population_adult"] = pd.to_numeric(valid["Population_adult"], errors="coerce")

        valid = valid.dropna(subset=[col, "Population_adult"])

        if valid.empty or total_population == 0:
            row[col] = pd.NA
            continue

        available_population = valid["Population_adult"].sum()
        missing_population = total_population - available_population

        if missing_population / total_population > (1 / 3):
            row[col] = pd.NA
        else:
            row[col] = (
                (valid[col] * valid["Population_adult"]).sum()
                / valid["Population_adult"].sum()
            )

    ssa_rows.append(row)

ssa_data = pd.DataFrame(ssa_rows)

In [4]:
ssa_data

,Region,Code,Year,Population_adult,Account,Digitally enabled Account,Made a Digital Payment,Mobile Money Account,Internet_users,GDP,...,Borrowed any money from a formal bank or similar financial institution or using a mobile money account (% age 15+),Borrowed from a formal bank or similar financial institution (% age 15+),"Mobile money account, men (% age 15+)","Mobile money account, women (% age 15+)",Saved at a bank or similar financial institution (% age 15+),Saved at a bank or similar financial institution or using a mobile money account (% age 15+),Saved money using a mobile money account (% age 15+),"Sent money from a mobile money account, less than once a month (% age 15+)","Sent or withdrew money from a bank or similar financial institution, monthly (%, age 15+) (% age 15+)","Sent or withdrew money from a mobile money account, Never (% age 15+) (% age 15+)"
0,Sub-Saharan Africa,SSA,2011,506340043.0,23.263596,<NA>,<NA>,<NA>,8.247260,1922.945529,...,<NA>,<NA>,<NA>,<NA>,13.845363,13.845363,<NA>,<NA>,<NA>,<NA>
1,Sub-Saharan Africa,SSA,2014,553446901.0,34.057258,<NA>,22.507894,11.864912,14.311837,2006.648474,...,7.483658,7.483658,<NA>,<NA>,16.022629,16.022629,<NA>,<NA>,<NA>,<NA>
2,Sub-Saharan Africa,SSA,2017,605551456.0,42.435504,<NA>,28.878837,20.927124,21.999043,1657.999788,...,8.315231,8.315231,<NA>,<NA>,14.88205,14.88205,<NA>,<NA>,<NA>,<NA>
3,Sub-Saharan Africa,SSA,2021,685227275.0,<NA>,<NA>,<NA>,<NA>,30.215520,1903.193910,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,Sub-Saharan Africa,SSA,2022,706240491.0,<NA>,<NA>,<NA>,<NA>,32.627264,1975.735120,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5,Sub-Saharan Africa,SSA,2024,750038608.0,58.118123,48.796392,44.558734,40.160242,35.062070,1631.894633,...,12.418115,6.808196,51.415408,39.472272,19.664426,34.660853,22.92598,14.919659,11.869486,2.04857

In [5]:
print(ssa_data.columns)

Index(['Region', 'Code', 'Year', 'Population_adult', 'Account',
       'Digitally enabled Account', 'Made a Digital Payment',
       'Mobile Money Account', 'Internet_users', 'GDP',
       'Mobile_cellular_subscription', 'Commercial_bank_branches',
       'Poverty_ratio', 'Urban_population', 'Bank Account',
       'Financial_Institution_Account_only', 'Mobile_Money_Account_only',
       'Both_Accounts', 'Borrowed from a mobile money provider  (% age 15+)',
       'Received government payments  (% age 15+)',
       'Received government payments: in cash only (% of government payment recipients, age 15+)',
       'Received government payments: into a bank or similar financial institution account (% of government payment recipients, age 15+)',
       'Received government payments: into an account (% of government payment recipients, age 15+)',
       'Received government payments: through a mobile phone (% of government payment recipients, age 15+)',
       'Received government payments: to a card (% of government payment recipients, age 15+)',
       'Received private sector wages  (% age 15+)',
       'Received private sector wages: in cash only (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into a bank or similar financial institution account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: into an account (% of private sector wage recipients, age 15+)',
       'Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)',
       'Received private sector wages: to a card (% of private sector wage recipients, age 15+)',
       'Saved any money  (% age 15+)',
       'Received payments for agricultural products: in cash only (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: into an account (% of agricultural payment recipients, age 15+)',
       'Received payments for agricultural products: through a mobile phone (% payment recipients, age 15+)',
       'Bank or similar financial institution account, men (% age 15+)',
       'Bank or similar financial institution account, women (% age 15+)',
       'Borrowed any money from a formal bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Borrowed from a formal bank or similar financial institution  (% age 15+)',
       'Mobile money account, men (% age 15+)',
       'Mobile money account, women (% age 15+)',
       'Saved at a bank or similar financial institution  (% age 15+)',
       'Saved at a bank or similar financial institution or using a mobile money account  (% age 15+)',
       'Saved money using a mobile money account  (% age 15+)',
       'Sent money from a mobile money account, less than once a month  (% age 15+)',
       'Sent or withdrew money from a bank or similar financial institution, monthly (%,  age 15+) (% age 15+)',
       'Sent or withdrew money from a mobile money account, Never (%  age 15+) (% age 15+)'],
      dtype='str')

In [6]:
ssa_data.shape[1]

47

In [7]:
ssa_data['Borrowed from a formal bank or similar financial institution  (% age 15+)']

0        <NA>
1    7.483658
2    8.315231
3        <NA>
4        <NA>
5    6.808196
Name: Borrowed from a formal bank or similar financial institution  (% age 15+), dtype: object

In [13]:
master.loc[
    (master["Year"] == 2011) &
    (master["Country"] == "Kenya"),
    [
        "Year",
        "Account",
        "Mobile Money Account",
        "Financial_Institution_Account_only",
        "Both_Accounts",
        "Mobile_Money_Account_only",
        "Bank Account"
    ]
]

,Year,Account,Mobile Money Account,Financial_Institution_Account_only,Both_Accounts,Mobile_Money_Account_only,Bank Account
108,2011,42.343454,NaN,NaN,NaN,0.0,42.343454

In [9]:
master[master["Year"] == 2021].shape

(43, 47)

In [10]:
year_2021 = master[master["Year"] == 2021]

year_2021["Account"].notna().sum()

np.int64(25)

In [11]:
ssa_2021 = ssa_data.loc[
    ssa_data["Year"] == 2017,
    [
      'Mobile money account, men (% age 15+)',
       'Mobile money account, women (% age 15+)',
    ]
]


ssa_2021

,"Mobile money account, men (% age 15+)","Mobile money account, women (% age 15+)"
2,<NA>,<NA>

In [12]:
year_2021 = master[master["Year"] == 2021]

total_pop = year_2021["Population_adult"].sum()

for col in [
    "Account",
    "Mobile Money Account",
    "Financial_Institution_Account_only",
    "Both_Accounts"
]:
    available_pop = year_2021.loc[
        year_2021[col].notna(),
        "Population_adult"
    ].sum()

    coverage = available_pop / total_pop

    print(col, f"{coverage:.2%}")

Account 64.95%
Mobile Money Account 64.95%
Financial_Institution_Account_only 64.95%
Both_Accounts 64.95%